# Generated by Django 3.1.1 on 2021-05-22 12:01

from django.db import migrations, models
import elephant.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210522_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.FileField(null=True, upload_to=elephant.utils.utils.PathAndRename('account/avatar')),
        ),
    ]
