# Generated by Django 3.1.1 on 2021-05-21 14:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={}, encoder=rest_framework.utils.encoders.JSONEncoder)),
            ],
        ),
    ]
