# Generated by Django 3.1.1 on 2021-05-21 14:22

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210521_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='data',
            field=models.JSONField(default=dict, encoder=rest_framework.utils.encoders.JSONEncoder),
        ),
    ]
